//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZEN.SaleAndTranfer.UI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MainEntities : DbContext
    {
        public MainEntities()
            : base("name=MainEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<USP_R_ST_MAP_PR_CATEGORY_BRAND_GetByBrandCode_Result> USP_R_ST_MAP_PR_CATEGORY_BRAND_GetByBrandCode(string p_BRAND_CODE, Nullable<bool> p_ACTIVE_FLAG)
        {
            var p_BRAND_CODEParameter = p_BRAND_CODE != null ?
                new ObjectParameter("P_BRAND_CODE", p_BRAND_CODE) :
                new ObjectParameter("P_BRAND_CODE", typeof(string));
    
            var p_ACTIVE_FLAGParameter = p_ACTIVE_FLAG.HasValue ?
                new ObjectParameter("P_ACTIVE_FLAG", p_ACTIVE_FLAG) :
                new ObjectParameter("P_ACTIVE_FLAG", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_R_ST_MAP_PR_CATEGORY_BRAND_GetByBrandCode_Result>("USP_R_ST_MAP_PR_CATEGORY_BRAND_GetByBrandCode", p_BRAND_CODEParameter, p_ACTIVE_FLAGParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> USP_R_ST_MAP_WH_ITEM__SearchCountAll(Nullable<int> sT_PR_CATEGORY_ID, string iTEM_CODE, string iTEM_NAME, string orderByList, Nullable<int> pageSize, Nullable<int> currentPageId, string username)
        {
            var sT_PR_CATEGORY_IDParameter = sT_PR_CATEGORY_ID.HasValue ?
                new ObjectParameter("ST_PR_CATEGORY_ID", sT_PR_CATEGORY_ID) :
                new ObjectParameter("ST_PR_CATEGORY_ID", typeof(int));
    
            var iTEM_CODEParameter = iTEM_CODE != null ?
                new ObjectParameter("ITEM_CODE", iTEM_CODE) :
                new ObjectParameter("ITEM_CODE", typeof(string));
    
            var iTEM_NAMEParameter = iTEM_NAME != null ?
                new ObjectParameter("ITEM_NAME", iTEM_NAME) :
                new ObjectParameter("ITEM_NAME", typeof(string));
    
            var orderByListParameter = orderByList != null ?
                new ObjectParameter("OrderByList", orderByList) :
                new ObjectParameter("OrderByList", typeof(string));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            var currentPageIdParameter = currentPageId.HasValue ?
                new ObjectParameter("CurrentPageId", currentPageId) :
                new ObjectParameter("CurrentPageId", typeof(int));
    
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("USP_R_ST_MAP_WH_ITEM__SearchCountAll", sT_PR_CATEGORY_IDParameter, iTEM_CODEParameter, iTEM_NAMEParameter, orderByListParameter, pageSizeParameter, currentPageIdParameter, usernameParameter);
        }
    
        public virtual ObjectResult<string> USP_R_ST_PR_H_Insert_V2(string bRANCH_CODE, Nullable<System.DateTime> pLAN_DELIVERY_DATE, string cREATE_BY, string mOBILE_NO, string cUS_PO_CODE, string pR_REMARK, string pR_BY, string aDDR, string aDDR2, string aDDR3, string pOSTCODE, string cITY, string iS_SALE_ADMIN, string sALE_ADMIN_CODE)
        {
            var bRANCH_CODEParameter = bRANCH_CODE != null ?
                new ObjectParameter("BRANCH_CODE", bRANCH_CODE) :
                new ObjectParameter("BRANCH_CODE", typeof(string));
    
            var pLAN_DELIVERY_DATEParameter = pLAN_DELIVERY_DATE.HasValue ?
                new ObjectParameter("PLAN_DELIVERY_DATE", pLAN_DELIVERY_DATE) :
                new ObjectParameter("PLAN_DELIVERY_DATE", typeof(System.DateTime));
    
            var cREATE_BYParameter = cREATE_BY != null ?
                new ObjectParameter("CREATE_BY", cREATE_BY) :
                new ObjectParameter("CREATE_BY", typeof(string));
    
            var mOBILE_NOParameter = mOBILE_NO != null ?
                new ObjectParameter("MOBILE_NO", mOBILE_NO) :
                new ObjectParameter("MOBILE_NO", typeof(string));
    
            var cUS_PO_CODEParameter = cUS_PO_CODE != null ?
                new ObjectParameter("CUS_PO_CODE", cUS_PO_CODE) :
                new ObjectParameter("CUS_PO_CODE", typeof(string));
    
            var pR_REMARKParameter = pR_REMARK != null ?
                new ObjectParameter("PR_REMARK", pR_REMARK) :
                new ObjectParameter("PR_REMARK", typeof(string));
    
            var pR_BYParameter = pR_BY != null ?
                new ObjectParameter("PR_BY", pR_BY) :
                new ObjectParameter("PR_BY", typeof(string));
    
            var aDDRParameter = aDDR != null ?
                new ObjectParameter("ADDR", aDDR) :
                new ObjectParameter("ADDR", typeof(string));
    
            var aDDR2Parameter = aDDR2 != null ?
                new ObjectParameter("ADDR2", aDDR2) :
                new ObjectParameter("ADDR2", typeof(string));
    
            var aDDR3Parameter = aDDR3 != null ?
                new ObjectParameter("ADDR3", aDDR3) :
                new ObjectParameter("ADDR3", typeof(string));
    
            var pOSTCODEParameter = pOSTCODE != null ?
                new ObjectParameter("POSTCODE", pOSTCODE) :
                new ObjectParameter("POSTCODE", typeof(string));
    
            var cITYParameter = cITY != null ?
                new ObjectParameter("CITY", cITY) :
                new ObjectParameter("CITY", typeof(string));
    
            var iS_SALE_ADMINParameter = iS_SALE_ADMIN != null ?
                new ObjectParameter("IS_SALE_ADMIN", iS_SALE_ADMIN) :
                new ObjectParameter("IS_SALE_ADMIN", typeof(string));
    
            var sALE_ADMIN_CODEParameter = sALE_ADMIN_CODE != null ?
                new ObjectParameter("SALE_ADMIN_CODE", sALE_ADMIN_CODE) :
                new ObjectParameter("SALE_ADMIN_CODE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("USP_R_ST_PR_H_Insert_V2", bRANCH_CODEParameter, pLAN_DELIVERY_DATEParameter, cREATE_BYParameter, mOBILE_NOParameter, cUS_PO_CODEParameter, pR_REMARKParameter, pR_BYParameter, aDDRParameter, aDDR2Parameter, aDDR3Parameter, pOSTCODEParameter, cITYParameter, iS_SALE_ADMINParameter, sALE_ADMIN_CODEParameter);
        }
    
        public virtual int USP_R_ST_PR_D_Insert_V2(Nullable<int> stMapWhItemID, Nullable<decimal> orderQty, string itemCode, string requestUomCode, string itemName, Nullable<decimal> unitPrice, string remark, string createBy, string prCode, string brandCode, string branchCode)
        {
            var stMapWhItemIDParameter = stMapWhItemID.HasValue ?
                new ObjectParameter("StMapWhItemID", stMapWhItemID) :
                new ObjectParameter("StMapWhItemID", typeof(int));
    
            var orderQtyParameter = orderQty.HasValue ?
                new ObjectParameter("OrderQty", orderQty) :
                new ObjectParameter("OrderQty", typeof(decimal));
    
            var itemCodeParameter = itemCode != null ?
                new ObjectParameter("ItemCode", itemCode) :
                new ObjectParameter("ItemCode", typeof(string));
    
            var requestUomCodeParameter = requestUomCode != null ?
                new ObjectParameter("RequestUomCode", requestUomCode) :
                new ObjectParameter("RequestUomCode", typeof(string));
    
            var itemNameParameter = itemName != null ?
                new ObjectParameter("ItemName", itemName) :
                new ObjectParameter("ItemName", typeof(string));
    
            var unitPriceParameter = unitPrice.HasValue ?
                new ObjectParameter("UnitPrice", unitPrice) :
                new ObjectParameter("UnitPrice", typeof(decimal));
    
            var remarkParameter = remark != null ?
                new ObjectParameter("Remark", remark) :
                new ObjectParameter("Remark", typeof(string));
    
            var createByParameter = createBy != null ?
                new ObjectParameter("CreateBy", createBy) :
                new ObjectParameter("CreateBy", typeof(string));
    
            var prCodeParameter = prCode != null ?
                new ObjectParameter("PrCode", prCode) :
                new ObjectParameter("PrCode", typeof(string));
    
            var brandCodeParameter = brandCode != null ?
                new ObjectParameter("BrandCode", brandCode) :
                new ObjectParameter("BrandCode", typeof(string));
    
            var branchCodeParameter = branchCode != null ?
                new ObjectParameter("BranchCode", branchCode) :
                new ObjectParameter("BranchCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_R_ST_PR_D_Insert_V2", stMapWhItemIDParameter, orderQtyParameter, itemCodeParameter, requestUomCodeParameter, itemNameParameter, unitPriceParameter, remarkParameter, createByParameter, prCodeParameter, brandCodeParameter, branchCodeParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> USP_R_ST_PR_SearchCountAll_V2(string prCode, Nullable<System.DateTime> planDeliveryDateFrom, Nullable<System.DateTime> planDeliveryDateTo, Nullable<System.DateTime> createDateFrom, Nullable<System.DateTime> createDateTo, string customerPoCode, string username, string orderByList, Nullable<int> pageSize, Nullable<int> currentPageId, string iS_SALE_ADMIN, string sALE_ADMIN_CODE, string nAME_2)
        {
            var prCodeParameter = prCode != null ?
                new ObjectParameter("PrCode", prCode) :
                new ObjectParameter("PrCode", typeof(string));
    
            var planDeliveryDateFromParameter = planDeliveryDateFrom.HasValue ?
                new ObjectParameter("PlanDeliveryDateFrom", planDeliveryDateFrom) :
                new ObjectParameter("PlanDeliveryDateFrom", typeof(System.DateTime));
    
            var planDeliveryDateToParameter = planDeliveryDateTo.HasValue ?
                new ObjectParameter("PlanDeliveryDateTo", planDeliveryDateTo) :
                new ObjectParameter("PlanDeliveryDateTo", typeof(System.DateTime));
    
            var createDateFromParameter = createDateFrom.HasValue ?
                new ObjectParameter("CreateDateFrom", createDateFrom) :
                new ObjectParameter("CreateDateFrom", typeof(System.DateTime));
    
            var createDateToParameter = createDateTo.HasValue ?
                new ObjectParameter("CreateDateTo", createDateTo) :
                new ObjectParameter("CreateDateTo", typeof(System.DateTime));
    
            var customerPoCodeParameter = customerPoCode != null ?
                new ObjectParameter("CustomerPoCode", customerPoCode) :
                new ObjectParameter("CustomerPoCode", typeof(string));
    
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            var orderByListParameter = orderByList != null ?
                new ObjectParameter("OrderByList", orderByList) :
                new ObjectParameter("OrderByList", typeof(string));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            var currentPageIdParameter = currentPageId.HasValue ?
                new ObjectParameter("CurrentPageId", currentPageId) :
                new ObjectParameter("CurrentPageId", typeof(int));
    
            var iS_SALE_ADMINParameter = iS_SALE_ADMIN != null ?
                new ObjectParameter("IS_SALE_ADMIN", iS_SALE_ADMIN) :
                new ObjectParameter("IS_SALE_ADMIN", typeof(string));
    
            var sALE_ADMIN_CODEParameter = sALE_ADMIN_CODE != null ?
                new ObjectParameter("SALE_ADMIN_CODE", sALE_ADMIN_CODE) :
                new ObjectParameter("SALE_ADMIN_CODE", typeof(string));
    
            var nAME_2Parameter = nAME_2 != null ?
                new ObjectParameter("NAME_2", nAME_2) :
                new ObjectParameter("NAME_2", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("USP_R_ST_PR_SearchCountAll_V2", prCodeParameter, planDeliveryDateFromParameter, planDeliveryDateToParameter, createDateFromParameter, createDateToParameter, customerPoCodeParameter, usernameParameter, orderByListParameter, pageSizeParameter, currentPageIdParameter, iS_SALE_ADMINParameter, sALE_ADMIN_CODEParameter, nAME_2Parameter);
        }
    
        public virtual ObjectResult<Nullable<int>> USP_COMMON_SearchResult__GetPageSize(string pageName)
        {
            var pageNameParameter = pageName != null ?
                new ObjectParameter("PageName", pageName) :
                new ObjectParameter("PageName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("USP_COMMON_SearchResult__GetPageSize", pageNameParameter);
        }
    
        public virtual ObjectResult<USP_R_ST_MAP_WH_ITEM__Search_Result> USP_R_ST_MAP_WH_ITEM__Search(Nullable<int> sT_PR_CATEGORY_ID, string iTEM_CODE, string iTEM_NAME, string orderByList, Nullable<int> pageSize, Nullable<int> currentPageId, string username, string branchCode, string brandCode)
        {
            var sT_PR_CATEGORY_IDParameter = sT_PR_CATEGORY_ID.HasValue ?
                new ObjectParameter("ST_PR_CATEGORY_ID", sT_PR_CATEGORY_ID) :
                new ObjectParameter("ST_PR_CATEGORY_ID", typeof(int));
    
            var iTEM_CODEParameter = iTEM_CODE != null ?
                new ObjectParameter("ITEM_CODE", iTEM_CODE) :
                new ObjectParameter("ITEM_CODE", typeof(string));
    
            var iTEM_NAMEParameter = iTEM_NAME != null ?
                new ObjectParameter("ITEM_NAME", iTEM_NAME) :
                new ObjectParameter("ITEM_NAME", typeof(string));
    
            var orderByListParameter = orderByList != null ?
                new ObjectParameter("OrderByList", orderByList) :
                new ObjectParameter("OrderByList", typeof(string));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            var currentPageIdParameter = currentPageId.HasValue ?
                new ObjectParameter("CurrentPageId", currentPageId) :
                new ObjectParameter("CurrentPageId", typeof(int));
    
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            var branchCodeParameter = branchCode != null ?
                new ObjectParameter("BranchCode", branchCode) :
                new ObjectParameter("BranchCode", typeof(string));
    
            var brandCodeParameter = brandCode != null ?
                new ObjectParameter("BrandCode", brandCode) :
                new ObjectParameter("BrandCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_R_ST_MAP_WH_ITEM__Search_Result>("USP_R_ST_MAP_WH_ITEM__Search", sT_PR_CATEGORY_IDParameter, iTEM_CODEParameter, iTEM_NAMEParameter, orderByListParameter, pageSizeParameter, currentPageIdParameter, usernameParameter, branchCodeParameter, brandCodeParameter);
        }
    
        public virtual ObjectResult<USP_R_ST_PR_Search_V2_Result> USP_R_ST_PR_Search_V2(string prCode, Nullable<System.DateTime> planDeliveryDateFrom, Nullable<System.DateTime> planDeliveryDateTo, Nullable<System.DateTime> createDateFrom, Nullable<System.DateTime> createDateTo, string customerPoCode, string username, string orderByList, Nullable<int> pageSize, Nullable<int> currentPageId, string iS_SALE_ADMIN, string sALE_ADMIN_CODE, string nAME_2)
        {
            var prCodeParameter = prCode != null ?
                new ObjectParameter("PrCode", prCode) :
                new ObjectParameter("PrCode", typeof(string));
    
            var planDeliveryDateFromParameter = planDeliveryDateFrom.HasValue ?
                new ObjectParameter("PlanDeliveryDateFrom", planDeliveryDateFrom) :
                new ObjectParameter("PlanDeliveryDateFrom", typeof(System.DateTime));
    
            var planDeliveryDateToParameter = planDeliveryDateTo.HasValue ?
                new ObjectParameter("PlanDeliveryDateTo", planDeliveryDateTo) :
                new ObjectParameter("PlanDeliveryDateTo", typeof(System.DateTime));
    
            var createDateFromParameter = createDateFrom.HasValue ?
                new ObjectParameter("CreateDateFrom", createDateFrom) :
                new ObjectParameter("CreateDateFrom", typeof(System.DateTime));
    
            var createDateToParameter = createDateTo.HasValue ?
                new ObjectParameter("CreateDateTo", createDateTo) :
                new ObjectParameter("CreateDateTo", typeof(System.DateTime));
    
            var customerPoCodeParameter = customerPoCode != null ?
                new ObjectParameter("CustomerPoCode", customerPoCode) :
                new ObjectParameter("CustomerPoCode", typeof(string));
    
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            var orderByListParameter = orderByList != null ?
                new ObjectParameter("OrderByList", orderByList) :
                new ObjectParameter("OrderByList", typeof(string));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            var currentPageIdParameter = currentPageId.HasValue ?
                new ObjectParameter("CurrentPageId", currentPageId) :
                new ObjectParameter("CurrentPageId", typeof(int));
    
            var iS_SALE_ADMINParameter = iS_SALE_ADMIN != null ?
                new ObjectParameter("IS_SALE_ADMIN", iS_SALE_ADMIN) :
                new ObjectParameter("IS_SALE_ADMIN", typeof(string));
    
            var sALE_ADMIN_CODEParameter = sALE_ADMIN_CODE != null ?
                new ObjectParameter("SALE_ADMIN_CODE", sALE_ADMIN_CODE) :
                new ObjectParameter("SALE_ADMIN_CODE", typeof(string));
    
            var nAME_2Parameter = nAME_2 != null ?
                new ObjectParameter("NAME_2", nAME_2) :
                new ObjectParameter("NAME_2", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_R_ST_PR_Search_V2_Result>("USP_R_ST_PR_Search_V2", prCodeParameter, planDeliveryDateFromParameter, planDeliveryDateToParameter, createDateFromParameter, createDateToParameter, customerPoCodeParameter, usernameParameter, orderByListParameter, pageSizeParameter, currentPageIdParameter, iS_SALE_ADMINParameter, sALE_ADMIN_CODEParameter, nAME_2Parameter);
        }
    
        public virtual ObjectResult<USP_R_ST_PR_H__GetByPK_Result> USP_R_ST_PR_H__GetByPK(string prCode)
        {
            var prCodeParameter = prCode != null ?
                new ObjectParameter("PrCode", prCode) :
                new ObjectParameter("PrCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_R_ST_PR_H__GetByPK_Result>("USP_R_ST_PR_H__GetByPK", prCodeParameter);
        }
    
        public virtual int USP_C_CONFIG__SavePopupPromotionItem(string itemCodes, string updateBy)
        {
            var itemCodesParameter = itemCodes != null ?
                new ObjectParameter("ItemCodes", itemCodes) :
                new ObjectParameter("ItemCodes", typeof(string));
    
            var updateByParameter = updateBy != null ?
                new ObjectParameter("UpdateBy", updateBy) :
                new ObjectParameter("UpdateBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_C_CONFIG__SavePopupPromotionItem", itemCodesParameter, updateByParameter);
        }
    
        public virtual ObjectResult<USP_C_CONFIG__GetPopupPromoItem_Result> USP_C_CONFIG__GetPopupPromoItem()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_C_CONFIG__GetPopupPromoItem_Result>("USP_C_CONFIG__GetPopupPromoItem");
        }
    
        public virtual ObjectResult<Nullable<bool>> USP_C_CONFIG__HasPopupPromoItem()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<bool>>("USP_C_CONFIG__HasPopupPromoItem");
        }
    
        public virtual ObjectResult<string> USP_R_ST_MAP_WH_ITEM__GetPopupPromoItem(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("USP_R_ST_MAP_WH_ITEM__GetPopupPromoItem", usernameParameter);
        }
    
        public virtual ObjectResult<USP_M_USM_USER__Search_V2_Result> USP_M_USM_USER__Search_V2(string username, string employeeID, string firstName, string lastName, string email, Nullable<bool> activeFlag, string branch, string roleName, string orderByList, Nullable<int> pageSize, Nullable<int> currentPageId)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            var employeeIDParameter = employeeID != null ?
                new ObjectParameter("EmployeeID", employeeID) :
                new ObjectParameter("EmployeeID", typeof(string));
    
            var firstNameParameter = firstName != null ?
                new ObjectParameter("FirstName", firstName) :
                new ObjectParameter("FirstName", typeof(string));
    
            var lastNameParameter = lastName != null ?
                new ObjectParameter("LastName", lastName) :
                new ObjectParameter("LastName", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var activeFlagParameter = activeFlag.HasValue ?
                new ObjectParameter("ActiveFlag", activeFlag) :
                new ObjectParameter("ActiveFlag", typeof(bool));
    
            var branchParameter = branch != null ?
                new ObjectParameter("Branch", branch) :
                new ObjectParameter("Branch", typeof(string));
    
            var roleNameParameter = roleName != null ?
                new ObjectParameter("RoleName", roleName) :
                new ObjectParameter("RoleName", typeof(string));
    
            var orderByListParameter = orderByList != null ?
                new ObjectParameter("OrderByList", orderByList) :
                new ObjectParameter("OrderByList", typeof(string));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            var currentPageIdParameter = currentPageId.HasValue ?
                new ObjectParameter("CurrentPageId", currentPageId) :
                new ObjectParameter("CurrentPageId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_M_USM_USER__Search_V2_Result>("USP_M_USM_USER__Search_V2", usernameParameter, employeeIDParameter, firstNameParameter, lastNameParameter, emailParameter, activeFlagParameter, branchParameter, roleNameParameter, orderByListParameter, pageSizeParameter, currentPageIdParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> USP_M_USM_USER__SearchCountAll_V2(string username, string employeeID, string firstName, string lastName, string email, Nullable<bool> activeFlag, string branch, string roleName, string orderByList, Nullable<int> pageSize, Nullable<int> currentPageId)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            var employeeIDParameter = employeeID != null ?
                new ObjectParameter("EmployeeID", employeeID) :
                new ObjectParameter("EmployeeID", typeof(string));
    
            var firstNameParameter = firstName != null ?
                new ObjectParameter("FirstName", firstName) :
                new ObjectParameter("FirstName", typeof(string));
    
            var lastNameParameter = lastName != null ?
                new ObjectParameter("LastName", lastName) :
                new ObjectParameter("LastName", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var activeFlagParameter = activeFlag.HasValue ?
                new ObjectParameter("ActiveFlag", activeFlag) :
                new ObjectParameter("ActiveFlag", typeof(bool));
    
            var branchParameter = branch != null ?
                new ObjectParameter("Branch", branch) :
                new ObjectParameter("Branch", typeof(string));
    
            var roleNameParameter = roleName != null ?
                new ObjectParameter("RoleName", roleName) :
                new ObjectParameter("RoleName", typeof(string));
    
            var orderByListParameter = orderByList != null ?
                new ObjectParameter("OrderByList", orderByList) :
                new ObjectParameter("OrderByList", typeof(string));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            var currentPageIdParameter = currentPageId.HasValue ?
                new ObjectParameter("CurrentPageId", currentPageId) :
                new ObjectParameter("CurrentPageId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("USP_M_USM_USER__SearchCountAll_V2", usernameParameter, employeeIDParameter, firstNameParameter, lastNameParameter, emailParameter, activeFlagParameter, branchParameter, roleNameParameter, orderByListParameter, pageSizeParameter, currentPageIdParameter);
        }
    
        public virtual ObjectResult<USP_M_USM_USER__Save_Result> USP_M_USM_USER__Save(string username, string passwrodHash, string employeeID, string firstNameTh, string lastNameTh, string email, Nullable<bool> activeFlag, string saveBy, string mode, string roleName, string branchCode)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            var passwrodHashParameter = passwrodHash != null ?
                new ObjectParameter("PasswrodHash", passwrodHash) :
                new ObjectParameter("PasswrodHash", typeof(string));
    
            var employeeIDParameter = employeeID != null ?
                new ObjectParameter("EmployeeID", employeeID) :
                new ObjectParameter("EmployeeID", typeof(string));
    
            var firstNameThParameter = firstNameTh != null ?
                new ObjectParameter("FirstNameTh", firstNameTh) :
                new ObjectParameter("FirstNameTh", typeof(string));
    
            var lastNameThParameter = lastNameTh != null ?
                new ObjectParameter("LastNameTh", lastNameTh) :
                new ObjectParameter("LastNameTh", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var activeFlagParameter = activeFlag.HasValue ?
                new ObjectParameter("ActiveFlag", activeFlag) :
                new ObjectParameter("ActiveFlag", typeof(bool));
    
            var saveByParameter = saveBy != null ?
                new ObjectParameter("SaveBy", saveBy) :
                new ObjectParameter("SaveBy", typeof(string));
    
            var modeParameter = mode != null ?
                new ObjectParameter("Mode", mode) :
                new ObjectParameter("Mode", typeof(string));
    
            var roleNameParameter = roleName != null ?
                new ObjectParameter("RoleName", roleName) :
                new ObjectParameter("RoleName", typeof(string));
    
            var branchCodeParameter = branchCode != null ?
                new ObjectParameter("BranchCode", branchCode) :
                new ObjectParameter("BranchCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_M_USM_USER__Save_Result>("USP_M_USM_USER__Save", usernameParameter, passwrodHashParameter, employeeIDParameter, firstNameThParameter, lastNameThParameter, emailParameter, activeFlagParameter, saveByParameter, modeParameter, roleNameParameter, branchCodeParameter);
        }
    
        public virtual ObjectResult<USP_M_USM_USER__GetByPK_V2_Result> USP_M_USM_USER__GetByPK_V2(string username)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_M_USM_USER__GetByPK_V2_Result>("USP_M_USM_USER__GetByPK_V2", usernameParameter);
        }
    
        public virtual int USP_M_USM_USER__UpdatePwd(string username, string passwordHash, string updateBy)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            var passwordHashParameter = passwordHash != null ?
                new ObjectParameter("PasswordHash", passwordHash) :
                new ObjectParameter("PasswordHash", typeof(string));
    
            var updateByParameter = updateBy != null ?
                new ObjectParameter("UpdateBy", updateBy) :
                new ObjectParameter("UpdateBy", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_M_USM_USER__UpdatePwd", usernameParameter, passwordHashParameter, updateByParameter);
        }
    
        public virtual ObjectResult<USP_R_BATCH_MASTER_Result> USP_R_BATCH_MASTER(string cREATE_BY, string pROCESS_TYPE)
        {
            var cREATE_BYParameter = cREATE_BY != null ?
                new ObjectParameter("CREATE_BY", cREATE_BY) :
                new ObjectParameter("CREATE_BY", typeof(string));
    
            var pROCESS_TYPEParameter = pROCESS_TYPE != null ?
                new ObjectParameter("PROCESS_TYPE", pROCESS_TYPE) :
                new ObjectParameter("PROCESS_TYPE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_R_BATCH_MASTER_Result>("USP_R_BATCH_MASTER", cREATE_BYParameter, pROCESS_TYPEParameter);
        }
    
        public virtual ObjectResult<USP_R_ST_PR_D__GetByPrCode_Result> USP_R_ST_PR_D__GetByPrCode(string prCode)
        {
            var prCodeParameter = prCode != null ?
                new ObjectParameter("PrCode", prCode) :
                new ObjectParameter("PrCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_R_ST_PR_D__GetByPrCode_Result>("USP_R_ST_PR_D__GetByPrCode", prCodeParameter);
        }
    
        public virtual ObjectResult<string> USP_R_ST_PR_SendToNavision(string p_ST_PR_CODE)
        {
            var p_ST_PR_CODEParameter = p_ST_PR_CODE != null ?
                new ObjectParameter("P_ST_PR_CODE", p_ST_PR_CODE) :
                new ObjectParameter("P_ST_PR_CODE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("USP_R_ST_PR_SendToNavision", p_ST_PR_CODEParameter);
        }
    
        public virtual int USP_R_ST_PR_H_Update_FLAG(string p_ST_PR_CODE, Nullable<bool> p_DELETE_FLAG, string p_UPDATE_BY)
        {
            var p_ST_PR_CODEParameter = p_ST_PR_CODE != null ?
                new ObjectParameter("P_ST_PR_CODE", p_ST_PR_CODE) :
                new ObjectParameter("P_ST_PR_CODE", typeof(string));
    
            var p_DELETE_FLAGParameter = p_DELETE_FLAG.HasValue ?
                new ObjectParameter("P_DELETE_FLAG", p_DELETE_FLAG) :
                new ObjectParameter("P_DELETE_FLAG", typeof(bool));
    
            var p_UPDATE_BYParameter = p_UPDATE_BY != null ?
                new ObjectParameter("P_UPDATE_BY", p_UPDATE_BY) :
                new ObjectParameter("P_UPDATE_BY", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_R_ST_PR_H_Update_FLAG", p_ST_PR_CODEParameter, p_DELETE_FLAGParameter, p_UPDATE_BYParameter);
        }
    
        public virtual ObjectResult<USP_M_USM_USER__Search_V2_Result> USP_M_USM_USER__Search(string username, string employeeID, string firstName, string lastName, string email, Nullable<bool> activeFlag, string branch, string roleName, string orderByList, Nullable<int> pageSize, Nullable<int> currentPageId)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            var employeeIDParameter = employeeID != null ?
                new ObjectParameter("EmployeeID", employeeID) :
                new ObjectParameter("EmployeeID", typeof(string));
    
            var firstNameParameter = firstName != null ?
                new ObjectParameter("FirstName", firstName) :
                new ObjectParameter("FirstName", typeof(string));
    
            var lastNameParameter = lastName != null ?
                new ObjectParameter("LastName", lastName) :
                new ObjectParameter("LastName", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var activeFlagParameter = activeFlag.HasValue ?
                new ObjectParameter("ActiveFlag", activeFlag) :
                new ObjectParameter("ActiveFlag", typeof(bool));
    
            var branchParameter = branch != null ?
                new ObjectParameter("Branch", branch) :
                new ObjectParameter("Branch", typeof(string));
    
            var roleNameParameter = roleName != null ?
                new ObjectParameter("RoleName", roleName) :
                new ObjectParameter("RoleName", typeof(string));
    
            var orderByListParameter = orderByList != null ?
                new ObjectParameter("OrderByList", orderByList) :
                new ObjectParameter("OrderByList", typeof(string));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            var currentPageIdParameter = currentPageId.HasValue ?
                new ObjectParameter("CurrentPageId", currentPageId) :
                new ObjectParameter("CurrentPageId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_M_USM_USER__Search_V2_Result>("USP_M_USM_USER__Search", usernameParameter, employeeIDParameter, firstNameParameter, lastNameParameter, emailParameter, activeFlagParameter, branchParameter, roleNameParameter, orderByListParameter, pageSizeParameter, currentPageIdParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> USP_M_USM_USER__SearchCountAll(string username, string employeeID, string firstName, string lastName, string email, Nullable<bool> activeFlag, string branch, string roleName, string orderByList, Nullable<int> pageSize, Nullable<int> currentPageId)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            var employeeIDParameter = employeeID != null ?
                new ObjectParameter("EmployeeID", employeeID) :
                new ObjectParameter("EmployeeID", typeof(string));
    
            var firstNameParameter = firstName != null ?
                new ObjectParameter("FirstName", firstName) :
                new ObjectParameter("FirstName", typeof(string));
    
            var lastNameParameter = lastName != null ?
                new ObjectParameter("LastName", lastName) :
                new ObjectParameter("LastName", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var activeFlagParameter = activeFlag.HasValue ?
                new ObjectParameter("ActiveFlag", activeFlag) :
                new ObjectParameter("ActiveFlag", typeof(bool));
    
            var branchParameter = branch != null ?
                new ObjectParameter("Branch", branch) :
                new ObjectParameter("Branch", typeof(string));
    
            var roleNameParameter = roleName != null ?
                new ObjectParameter("RoleName", roleName) :
                new ObjectParameter("RoleName", typeof(string));
    
            var orderByListParameter = orderByList != null ?
                new ObjectParameter("OrderByList", orderByList) :
                new ObjectParameter("OrderByList", typeof(string));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            var currentPageIdParameter = currentPageId.HasValue ?
                new ObjectParameter("CurrentPageId", currentPageId) :
                new ObjectParameter("CurrentPageId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("USP_M_USM_USER__SearchCountAll", usernameParameter, employeeIDParameter, firstNameParameter, lastNameParameter, emailParameter, activeFlagParameter, branchParameter, roleNameParameter, orderByListParameter, pageSizeParameter, currentPageIdParameter);
        }
    
        public virtual int USP_R_BATCH_SEND_ST_PR_SALE_MANUAL_KMF(string pRNO, string pRPCESS_BY, string pROCESS_TYPE,ObjectParameter resultFlag,ObjectParameter resultMsg)
        {
            var pRNOParameter = pRNO != null ?
                new ObjectParameter("PRNO", pRNO) :
                new ObjectParameter("PRNO", typeof(string));
    
            var pRPCESS_BYParameter = pRPCESS_BY != null ?
                new ObjectParameter("PRPCESS_BY", pRPCESS_BY) :
                new ObjectParameter("PRPCESS_BY", typeof(string));
    
            var pROCESS_TYPEParameter = pROCESS_TYPE != null ?
                new ObjectParameter("PROCESS_TYPE", pROCESS_TYPE) :
                new ObjectParameter("PROCESS_TYPE", typeof(string));

			var resultFlagParameter = resultFlag != null ?
				new ObjectParameter("ResultFlag", resultFlag) :
				new ObjectParameter("ResultFlag", typeof(int));

			var resultMsgParameter = resultMsg != null ?
				new ObjectParameter("ResultMsg", resultMsg) :
				new ObjectParameter("ResultMsg", typeof(string));
			return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_R_BATCH_SEND_ST_PR_SALE_MANUAL_KMF", pRNOParameter, pRPCESS_BYParameter, pROCESS_TYPEParameter, resultFlagParameter, resultMsgParameter);
        }
    }
}
